layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:

social_media:
  linkedin: colin-009
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: GoLang
    image_url: https://www.evanmiller.org/images/four-days-of-go/gopher3.png

  - name: Raspberry Pi
    # web_url: /raspberry-pi
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/raspberry-pi/raspberry-pi.png

  - name: IaC/Terraform
    # web_url: /ui-ux
    image_url: https://blogs.vmware.com/cloudprovider/files/2019/04/og-image-8b3e4f7d-blog-aspect-ratio-576x324.png

  - name: Amazon Web Services
    # web_url: /embedded
    image_url: https://uploads-ssl.webflow.com/604e9f1b3b8992ec0978e67f/63178de0492be32979c9acf7_aws-logo.png

  - name: Games
    # web_url: /embedded
    image_url: https://logos-world.net/wp-content/uploads/2021/11/Unity-Emblem.png
  
  - name: Android
    # web_url: /android
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/android/android.png
